 #类型转换
yue=2000
cunkuan='1000'
print('存款后，余额为：',yue+int(cunkuan))
#int是整形，可以把其转换为整形，如果不转就运行错误
#也可以在前面加一个cunkuan=int(cunkuan),后面就不用加int了。
#另外，第四行本来我没有加逗号分开，结果运行错误。
#不同类型的类型要想一起输出就需要用逗号分隔开
#转换为浮点型是float
#布尔型转换，是bool,有三种可以转化为False:a='';b=0;c=None。
a='';b=0;c=None
d=bool(a)
print(d)
#其他的都是True
#str是字符串
#注意只有数字可以转换为数字，转换要求形态要一致
